### PR TITLE
docs: Documentation changes

### PR DESCRIPTION
**Pull request by Devansh-Baghel**
## Changes made:
- Rename `Game-Idea.txt` to `README.md` (so that users don't have to click into the text file to read documentation)

## Before:
Screenshot from 2023-05-14 21-50-54

## After:
Screenshot from 2023-05-14 21-50-19

### CODE REVIEW

**Comment by Ashu104** [comment]
Hi @Devansh-Baghel
Nice to see your contribution as rename Game-Idea.txt to README.md 
But (what is think! ) changing the file extension may lead to confusion and break conventions with the main README.md file?

**Comment by Devansh-Baghel** [comment]
Hey, @Ashu104 
I think it's pretty standard to have a README inside a project directory that refers to that particular project. 

As this repo grows in size and number of projects, we can have each project in it's own directory and it's own README,
and to avoid confusion we can then add instructions in the main readme as to how the user shall proceed with their project!

I see you did something similar with [this pr.](https://github.com/hkirat/project-ideas/pull/16/files)

**Comment by Ashu104** [comment]
@Devansh-Baghel 
yahh. I did search for that doubt and also found that it is very obvious to use specific README for each directory. 
btw glad to see your concern!

**Review by nawabsahab16 — APPROVED** [review]

**Comment by Devansh-Baghel** [comment]
Closed due to inactivity

**Pull request closed without merging**
